# Generated by Django 2.2 on 2020-11-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='lastname',
        ),
    ]
