# Generated by Django 2.2 on 2020-11-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20201109_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='lname',
        ),
    ]
