# Generated by Django 2.2.4 on 2020-11-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ninja',
            name='updated_3at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
